# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d749d77a3806d100b54f846fbefb5ee63faacab9c9068ffb9866fb83e365df056fe9459c4576e6a26ecb81ba4ea465e306dae3b5b1a8b10e0c1eb0bb30f410d5

test:
  secret_key_base: 43265107419ee646a159b631868c80ea0843a2d24001c2bfd1eb2fa9af05cded546e4b743125b77c5b4ff4665dadaa6c7f26d93e3fb206571536425d787da173

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
